### ISSUE TITLE
Stylus Version

### ISSUE THREAD

**Issue by willhoag** [colindresj/saffron#13]
Hey! I switched to using Stylus recently and found myself missing your animation library, so I made a Stylus "fork" of your library at [willhoag/saffron-stylus](https://github.com/willhoag/saffron-stylus). Saffron-Stylus has a flattened folders and doesn't do any prefixing, but other then that it's a straight conversion. Thanks for the open source contribution!!! Open Source FTW!

**Comment by colindresj** [comment]
Cool! Sorry it took so long to respond, been a busy few months at work — I'll add a link to the wiki and readme
