### ISSUE TITLE
Some example documentation?

### ISSUE THREAD

**Issue by impressivewebs** [colindresj/saffron#14]
Sounds like a nice mixin library, but I don't see any example code to show how the mixin gets written, and what arguments it takes. Can you add a section in the README that has a few simple code examples, preferably one for both transitions and animations?

**Comment by impressivewebs** [comment]
Oh I just saw the one "teeter()" example... my bad... But maybe that should be under its own heading, because I totally missed it. Maybe call it "How to use" or whatever. And probably it would be good to include other examples too, or else list all the possible examples somewhere in the docs.

**Comment by colindresj** [comment]
The wiki has some basic docs on how to use: https://github.com/colindresj/saffron/wiki/Using-the-mixins

Probably not enough, so if you'd be willing to submit a PR for updates to the readme, I'd be happy to accept.
