### ISSUE TITLE
Compass compatibility

### ISSUE THREAD

**Issue by lemos** [colindresj/saffron#15]
¿Are you using Compass?
Looks like you mixin names are colliding with Compass: transform, transition, keyframes. Or maybe I'm doing something wrong.

**Comment by lemos** [comment]
I added the suffix "saf-" to that mixin names and it worked fine.
Can be useful the suffix as a namespace to avoid name collisions.
Regards
F

**Comment by colindresj** [comment]
Thanks for reporting @lemos. Never really been a compass user, so wouldn't have occurred to me. To be sure, just transform, transition and keyframes are colliding? 

If so, those are internal mixins, so would be find to namespace them in some way. I think either of `saf-` or `u-` makes sense.

I'm not too keen on renaming any of the public mixins if that's a problem.

**Comment by colindresj** [comment]
I'll update and release a new version with namespaced internal mixins soon.

**Comment by lemos** [comment]
Yes, that 3 mixins are the problem. But in any case, namespacing all internal mixins (prefix, animation) can be a good practice I think.

**Comment by lemos** [comment]
And this is off topic, but I added to variables  `$saf-duration: .5s !default;`

**Comment by colindresj** [comment]
Sorry for the delay on this. But pushed up a new version of the package to ruby gems and bower. If you're using the gem, just run `bundle update saffron`, then you can run a `saffron update` to update your source files. If you're using bower, then `bower update saffron` should do the trick.
